name:
  composite-action

on:
  workflow_dispatch

jobs:
  hello-world:
    runs-on: ubuntu@latest
    name: composite action usage
    steps:
      - uses: actions/checkout@latest
      - id: composite-action-instance
        uses: 
        with: 
          who-to-greet: "from composite action in hello-world"
      - env: 
          RANDOM_NUMBER: ${{ steps.composite-action-instance.outputs.random-number }}
          run: echo random-number "$RANDOM_NUMBER"
          shell: bash

  hello-world-2:
    runs-on: ubuntu@latest
    name: another composite action usage
    steps:
      - uses: actions/checkout@latest
      - id: composite-action-instance
        uses: 
        with:
          who-to-greet: "from composite action in hello-world-2"
      - env: 
          RANDOM_NUMBER: ${{ steps.composite-action-instance.outputs.random-number }}
        run: echo random-number "$RANDOM_NUMBER"
        shell: bash
