name: example one

on:
  push:
    branches: 
      - main

jobs:
  j1:
    steps:
      - run: echo "This is example one"
    runs-on: ubuntu-latest

  j2:
    runs-on: ubuntu-latest
    steps:
      - run: print("hello world")
        shell: python

  j3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "world"